# Build stage for Frontend
FROM node:alpine as client-build
WORKDIR /app/frontend
COPY client-build/electron_vue/package*.json ./
RUN npm install
COPY client/ .
RUN npm run dev
# Final container image for serving UI
FROM nginx:alpine
COPY --from=client-build /app/frontend/dist /usr/share/nginx/html/ui



